---
title: "git_00"
author: "Hayden Wood"
date: "Feburary 21st 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

In this git project we are adding poems and knit, commiting, and pushing.    
    
## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A BOAT beneath a sunny sky,     
Lingering onward dreamily     
In an evening of July --     
Children three that nestle near,      
Eager eye and willing ear,      

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,      
And sorry I could not travel both     
And be one traveler, long I stood        
And looked down one as far as I could        
To where it bent in the undergrowth;      

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,      
      Shining with all his might:      
He did his very best to make     
      The billows smooth and bright —     
And this was odd, because it was      
      The middle of the night.       
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

in placid densities. Water,         
water silken and plumbeous in opacity, in weight—Mercurial;      
water in suspense, slow water. The algal bloom         
brilliant—In the paps of pleasure. The algae, the        
bracing vapour of its peak;      
—across the arched silence, across the isthmuses      
of basalt; the algae, its abrasive rub,          
its slippage. Light water, fish water; the aura, the agate,         
its luminous border-breakings; Fire trailing the fleeing       


